# Generated by Django 4.2.6 on 2023-10-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('bn_name', models.CharField(max_length=100, verbose_name='Bangla Name')),
                ('lat', models.CharField(max_length=20, verbose_name='Latitude')),
                ('long', models.CharField(max_length=20, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
            ],
        ),
    ]
