# Generated by Django 4.2.6 on 2023-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name', 'bn_name', 'lat', 'long'], name='coolapp_dis_name_f7e06d_idx'),
        ),
    ]
