# Generated by Django 4.2.6 on 2023-10-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0004_temperatureforecast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemperatureForecast',
        ),
    ]
