# Generated by Django 4.2.6 on 2023-10-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0006_temperatureforecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatureforecast',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coolapp.district'),
        ),
    ]
