# Generated by Django 4.2.6 on 2023-10-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0007_temperatureforecast_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatureforecast',
            name='elevation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='temperatureforecast',
            name='generationtime_ms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='temperatureforecast',
            name='utc_offset_seconds',
            field=models.CharField(max_length=255),
        ),
    ]
