# Generated by Django 4.2.6 on 2023-10-27 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0008_alter_temperatureforecast_elevation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemperatureForecast',
        ),
    ]
