# Generated by Django 4.2.6 on 2023-10-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coolapp', '0009_delete_temperatureforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('generationtime_ms', models.FloatField()),
                ('utc_offset_seconds', models.IntegerField()),
                ('timezone', models.CharField(max_length=255)),
                ('timezone_abbreviation', models.CharField(max_length=10)),
                ('elevation', models.FloatField()),
                ('hourly_units_time', models.CharField(max_length=255)),
                ('hourly_units_temperature_2m', models.CharField(max_length=10)),
                ('hourly_time', models.JSONField()),
                ('hourly_temperature_2m', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(verbose_name='Last Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coolapp.district')),
            ],
        ),
    ]
